project_id = "fmajhzepqpnrzbtcdiix"

[functions.paystack-webhook]
verify_jwt = false

[functions.create-virtual-account]
verify_jwt = true

[functions.bulk-create-students]
verify_jwt = true

[functions.simulate-payment]
verify_jwt = true
